import React from "react";
import { PAPSection } from "./PAPSection";
import { PAPSectionHeader } from "./PAPSectionHeader";

/**
 * PAPDefinitions Component (Server Component)
 * 
 * Definitions section
 * Server-rendered for SEO
 */
export const PAPDefinitions: React.FC = () => {
  return (
    <>
      <PAPSection>
        <PAPSectionHeader
          title="Interpretation and Definitions Interpretation"
          icon="check"
        />
        <p className="text-lg">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions shall
          have the same meaning regardless of whether they appear in singular or
          in plural.
        </p>
      </PAPSection>

      <PAPSection>
        <PAPSectionHeader title="Definitions" />
        <p className="text-lg">For the purposes of this Privacy Policy:</p>
        <ul className="text-lg list-disc ml-10 space-y-3">
          <li>
            <b>Account</b> means a unique account created for You to access our
            Service or parts of our Service.
          </li>
          <li>
            <b>Affiliate</b> means an entity that controls, is controlled by or is
            under common control with a party, where &quot;control&quot; means
            ownership of 50% or more of the shares, equity interest or other
            securities entitled to vote for election of directors or other
            managing authority.
          </li>
          <li>
            <b>Application</b> refers to{" "}
            <span className="font-semibold text-P-primary">
              Easy Bangla Patente
            </span>
            , the software program provided by the Company.
          </li>
          <li>
            <b>Company</b> (referred to as either &quot;the Company&quot;,
            &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
            refers to{" "}
            <span className="font-semibold text-P-primary">
              Easy bangla Patente
            </span>
            .
          </li>
          <li>
            <b>Country</b> refers to: Italy
          </li>
          <li>
            <b>Device</b> means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </li>
          <li>
            <b>Personal</b> Data is any information that relates to an identified
            or identifiable individual.
          </li>
          <li>
            <b>Service</b> refers to the Application.
          </li>
          <li>
            <b>Service</b> Provider means any natural or legal person who
            processes the data on behalf of the Company. It refers to third-party
            companies or individuals employed by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform
            services related to the Service or to assist the Company in analyzing
            how the Service is used.
          </li>
          <li>
            <b>Usage</b> Data refers to data collected automatically, either
            generated by the use of the Service or from the Service infrastructure
            itself (for example, the duration of a page visit).
          </li>
          <li>
            <b>You</b> means the individual accessing or using the Service, or the
            company, or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </li>
        </ul>
      </PAPSection>
    </>
  );
};
